version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
    steps:
      - checkout
      - run: |
          pwd
          ls
          cd ..
          pwd
          ls
          cd ..
          pwd
          ls
          sudo pip install -r requirements.txt
          cd src
          python3 run_tests.py
