version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
    steps:
      - checkout
      - run: |
          sudo pip install -r requirments.txt
          cd src
          python3 run_tests.py
