version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
    steps:
      - checkout
      - run: |
          pwd
          sudo pip install -r requirements.txt
          pwd
