version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7-node-browsers-legacy
    steps:
    - checkout
    - run:
        name: Setup testing environment
        command: |
          pip install --upgrade pip
          sudo pip install coverage
          sudo pip install Twisted
          sudo pip install requests_threads
          sudo pip install -r requirments.txt
          cd src
    - run:
        name: Run Tests
        command: |
          coverage run -m pytest
          coverage report
          coverage html  # open htmlcov/index.html in a browser
    - store_artifacts:
        path: htmlcov
workflows:
  version: 2
  workflow:
    jobs:
    - build
